### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[283, 334, 313, 139], [283, 334, 313, 273], [283, 321, 313, 58], [114, 142, 157, 36, 353], [114, 142, 157, 36, 156], [164, 283, 194, 313, 41], [255, 311, 431, 36]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 283 334 313 139]
 [  0   0   0   0 283 334 313 273]
 [  0   0   0   0 283 321 313  58]
 [  0   0   0 114 142 157  36 353]
 [  0   0   0 114 142 157  36 156]
 [  0   0   0 164 283 194 313  41]
 [  0   0   0   0 255 311 431  36]]


In [11]:
## 10 feature dimesnions
dim=10


In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 283, 334, 313, 139], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 110ms/step


array([[ 0.01351861,  0.04277171,  0.01433312, -0.03494966,  0.00694761,
        -0.0046042 ,  0.01264625,  0.02411957,  0.02371191, -0.03973682],
       [ 0.01351861,  0.04277171,  0.01433312, -0.03494966,  0.00694761,
        -0.0046042 ,  0.01264625,  0.02411957,  0.02371191, -0.03973682],
       [ 0.01351861,  0.04277171,  0.01433312, -0.03494966,  0.00694761,
        -0.0046042 ,  0.01264625,  0.02411957,  0.02371191, -0.03973682],
       [ 0.01351861,  0.04277171,  0.01433312, -0.03494966,  0.00694761,
        -0.0046042 ,  0.01264625,  0.02411957,  0.02371191, -0.03973682],
       [ 0.01933931, -0.01913501,  0.02479087, -0.0464338 , -0.0104789 ,
         0.03317213,  0.00771096, -0.0261727 , -0.04084229,  0.01021664],
       [-0.01172125, -0.0041533 ,  0.02718084,  0.00468703, -0.01642243,
         0.00810901, -0.02421041,  0.00112935, -0.0355201 , -0.00731554],
       [ 0.03373287,  0.01466372, -0.04740348,  0.02409797, -0.04253915,
         0.03813111,  0.0148642 , -0.01822866

In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 35ms/step
[[[ 1.35186054e-02  4.27717082e-02  1.43331178e-02 -3.49496603e-02
    6.94761425e-03 -4.60419804e-03  1.26462467e-02  2.41195671e-02
    2.37119086e-02 -3.97368185e-02]
  [ 1.35186054e-02  4.27717082e-02  1.43331178e-02 -3.49496603e-02
    6.94761425e-03 -4.60419804e-03  1.26462467e-02  2.41195671e-02
    2.37119086e-02 -3.97368185e-02]
  [ 1.35186054e-02  4.27717082e-02  1.43331178e-02 -3.49496603e-02
    6.94761425e-03 -4.60419804e-03  1.26462467e-02  2.41195671e-02
    2.37119086e-02 -3.97368185e-02]
  [ 1.35186054e-02  4.27717082e-02  1.43331178e-02 -3.49496603e-02
    6.94761425e-03 -4.60419804e-03  1.26462467e-02  2.41195671e-02
    2.37119086e-02 -3.97368185e-02]
  [ 1.93393119e-02 -1.91350114e-02  2.47908719e-02 -4.64337952e-02
   -1.04789026e-02  3.31721343e-02  7.71095604e-03 -2.61726975e-02
   -4.08422947e-02  1.02166422e-02]
  [-1.17212534e-02 -4.15330008e-03  2.71808393e-02  4.68703359e-03
   -1.64224282e-02  8.10901076e

In [17]:
embedded_docs[0]

array([  0,   0,   0,   0, 283, 334, 313, 139], dtype=int32)

In [18]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 26ms/step
[[ 0.01351861  0.04277171  0.01433312 -0.03494966  0.00694761 -0.0046042
   0.01264625  0.02411957  0.02371191 -0.03973682]
 [ 0.01351861  0.04277171  0.01433312 -0.03494966  0.00694761 -0.0046042
   0.01264625  0.02411957  0.02371191 -0.03973682]
 [ 0.01351861  0.04277171  0.01433312 -0.03494966  0.00694761 -0.0046042
   0.01264625  0.02411957  0.02371191 -0.03973682]
 [ 0.01351861  0.04277171  0.01433312 -0.03494966  0.00694761 -0.0046042
   0.01264625  0.02411957  0.02371191 -0.03973682]
 [ 0.01933931 -0.01913501  0.02479087 -0.0464338  -0.0104789   0.03317213
   0.00771096 -0.0261727  -0.04084229  0.01021664]
 [-0.01172125 -0.0041533   0.02718084  0.00468703 -0.01642243  0.00810901
  -0.02421041  0.00112935 -0.0355201  -0.00731554]
 [ 0.03373287  0.01466372 -0.04740348  0.02409797 -0.04253915  0.03813111
   0.0148642  -0.01822866 -0.02310197  0.03238528]
 [-0.03722929  0.00343695 -0.01150391  0.02412074 -0.00315962 -0.01717357
   